#

pluginName = Discounts Model Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_Unknown_feature = Unspecified

_UI_Model_type = Model
_UI_Category_type = Category
_UI_Product_type = Product
_UI_Tag_type = Tag
_UI_Model_categories_feature = Categories
_UI_Model_tags_feature = Tags
_UI_Category_name_feature = Name
_UI_Category_subcategories_feature = Subcategories
_UI_Category_products_feature = Products
_UI_Product_name_feature = Name
_UI_Product_tags_feature = Tags
_UI_Tag_name_feature = Name
_UI_Offer_type = Offer
_UI_Trigger_type = Trigger
_UI_Condition_type = Condition
_UI_TaggedCondition_type = Tagged Condition
_UI_QuantityCondition_type = Quantity Condition
_UI_PriceCondition_type = Price Condition
_UI_DateCondition_type = Date Condition
_UI_Action_type = Action
_UI_TaggedDiscount_type = Tagged Discount
_UI_ProductDiscount_type = Product Discount
_UI_Model_offers_feature = Offers
_UI_Category_tags_feature = Tags
_UI_Offer_conditions_feature = Conditions
_UI_Offer_actions_feature = Actions
_UI_Offer_triggers_feature = Triggers
_UI_Trigger_triggerType_feature = Trigger Type
_UI_Trigger_offer_feature = Offer
_UI_TaggedCondition_tags_feature = Tags
_UI_TaggedCondition_quantity_feature = Quantity
_UI_TaggedCondition_comparison_feature = Comparison
_UI_QuantityCondition_product_feature = Product
_UI_QuantityCondition_quantity_feature = Quantity
_UI_QuantityCondition_comparison_feature = Comparison
_UI_PriceCondition_price_feature = Price
_UI_PriceCondition_comparison_feature = Comparison
_UI_DateCondition_startDate_feature = Start Date
_UI_DateCondition_endDate_feature = End Date
_UI_Action_percentageDiscount_feature = Percentage Discount
_UI_Action_quantityDiscount_feature = Quantity Discount
_UI_Action_priceDiscount_feature = Price Discount
_UI_Action_setPrice_feature = Set Price
_UI_TaggedDiscount_tags_feature = Tags
_UI_ProductDiscount_product_feature = Product
_UI_TriggerType_IF_MATCH_literal = IF_MATCH
_UI_TriggerType_IF_NOT_MATCH_literal = IF_NOT_MATCH
_UI_TriggerType_ALWAYS_literal = ALWAYS
_UI_Comparison_EQUAL_literal = EQUAL
_UI_Comparison_NOT_EQUAL_literal = NOT_EQUAL
_UI_Comparison_LESS_THAN_literal = LESS_THAN
_UI_Comparison_LESS_THAN_EQUAL_literal = LESS_THAN_EQUAL
_UI_Comparison_GREATER_THAN_literal = GREATER_THAN
_UI_Comparison_GREATER_THAN_EQUAL_literal = GREATER_THAN_EQUAL
_UI_ProductCondition_type = Product Condition
_UI_TaggedAction_type = Tagged Action
_UI_ProductAction_type = Product Action
_UI_ProductCondition_product_feature = Product
_UI_ProductCondition_quantity_feature = Quantity
_UI_ProductCondition_comparison_feature = Comparison
_UI_TaggedAction_tags_feature = Tags
_UI_ProductAction_product_feature = Product
_UI_Model_initialOffer_feature = Initial Offer
_UI_DailyCondition_type = Daily Condition
_UI_Offer_name_feature = Name
_UI_Condition_name_feature = Name
_UI_Action_name_feature = Name
_UI_DailyOrderCondition_type = Daily Order Condition
_UI_DateRangeCondition_type = Date Range Condition
_UI_DailyOrderCondition_product_feature = Product
_UI_DailyOrderCondition_comparison_feature = Comparison
_UI_DailyOrderCondition_threshold_feature = Threshold
_UI_DateRangeCondition_startDate_feature = Start Date
_UI_DateRangeCondition_endDate_feature = End Date
_UI_OrderDiscount_type = Order Discount
_UI_Model_products_feature = Products
_UI_TaggedDiscount_quantityDiscount_feature = Quantity Discount
_UI_ProductDiscount_quantityDiscount_feature = Quantity Discount
_UI_Trigger_triggerOn_feature = Trigger On
_UI_TriggerOn_ALWAYS_literal = ALWAYS
_UI_TriggerOn_MATCH_literal = MATCH
_UI_TriggerOn_NOT_MATCH_literal = NOT_MATCH
_UI_TriggerOn_IF_MATCH_literal = IF_MATCH
_UI_TriggerOn_IF_NOT_MATCH_literal = IF_NOT_MATCH
